com.liferay.portal\:com.liferay.portal.impl\:2.20.0=\
    com/liferay/portlet/asset/*,\
    com/liferay/portlet/asset/model/impl/*,\
    com/liferay/portlet/asset/service/base/*,\
    com/liferay/portlet/asset/service/http/*,\
    com/liferay/portlet/asset/service/impl/*,\
    com/liferay/portlet/asset/service/persistence/impl/*,\
    com/liferay/portlet/asset/social/*,\
    com/liferay/portlet/asset/util/comparator/*