/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.fragment.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.fragment.model.FragmentEntryLayoutTemplateLink;
import com.liferay.fragment.model.FragmentEntryLayoutTemplateLinkModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the FragmentEntryLayoutTemplateLink service. Represents a row in the &quot;FragmentEntryLayoutTemplateLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link FragmentEntryLayoutTemplateLinkModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FragmentEntryLayoutTemplateLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FragmentEntryLayoutTemplateLinkImpl
 * @see FragmentEntryLayoutTemplateLink
 * @see FragmentEntryLayoutTemplateLinkModel
 * @generated
 */
@ProviderType
public class FragmentEntryLayoutTemplateLinkModelImpl extends BaseModelImpl<FragmentEntryLayoutTemplateLink>
	implements FragmentEntryLayoutTemplateLinkModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fragment entry layout template link model instance should use the {@link FragmentEntryLayoutTemplateLink} interface instead.
	 */
	public static final String TABLE_NAME = "FragmentEntryLayoutTemplateLink";
	public static final Object[][] TABLE_COLUMNS = {
			{ "fragmentEntryLayoutTemplateLinkId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "fragmentEntryId", Types.BIGINT },
			{ "layoutPageTemplateEntryId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("fragmentEntryLayoutTemplateLinkId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fragmentEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("layoutPageTemplateEntryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table FragmentEntryLayoutTemplateLink (fragmentEntryLayoutTemplateLinkId LONG not null primary key,groupId LONG,fragmentEntryId LONG,layoutPageTemplateEntryId LONG)";
	public static final String TABLE_SQL_DROP = "drop table FragmentEntryLayoutTemplateLink";
	public static final String ORDER_BY_JPQL = " ORDER BY fragmentEntryLayoutTemplateLink.fragmentEntryLayoutTemplateLinkId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY FragmentEntryLayoutTemplateLink.fragmentEntryLayoutTemplateLinkId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.fragment.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.fragment.model.FragmentEntryLayoutTemplateLink"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.fragment.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.fragment.model.FragmentEntryLayoutTemplateLink"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.fragment.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.fragment.model.FragmentEntryLayoutTemplateLink"),
			true);
	public static final long FRAGMENTENTRYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long LAYOUTPAGETEMPLATEENTRYID_COLUMN_BITMASK = 4L;
	public static final long FRAGMENTENTRYLAYOUTTEMPLATELINKID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.fragment.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.fragment.model.FragmentEntryLayoutTemplateLink"));

	public FragmentEntryLayoutTemplateLinkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fragmentEntryLayoutTemplateLinkId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFragmentEntryLayoutTemplateLinkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fragmentEntryLayoutTemplateLinkId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FragmentEntryLayoutTemplateLink.class;
	}

	@Override
	public String getModelClassName() {
		return FragmentEntryLayoutTemplateLink.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("fragmentEntryLayoutTemplateLinkId",
			getFragmentEntryLayoutTemplateLinkId());
		attributes.put("groupId", getGroupId());
		attributes.put("fragmentEntryId", getFragmentEntryId());
		attributes.put("layoutPageTemplateEntryId",
			getLayoutPageTemplateEntryId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long fragmentEntryLayoutTemplateLinkId = (Long)attributes.get(
				"fragmentEntryLayoutTemplateLinkId");

		if (fragmentEntryLayoutTemplateLinkId != null) {
			setFragmentEntryLayoutTemplateLinkId(fragmentEntryLayoutTemplateLinkId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long fragmentEntryId = (Long)attributes.get("fragmentEntryId");

		if (fragmentEntryId != null) {
			setFragmentEntryId(fragmentEntryId);
		}

		Long layoutPageTemplateEntryId = (Long)attributes.get(
				"layoutPageTemplateEntryId");

		if (layoutPageTemplateEntryId != null) {
			setLayoutPageTemplateEntryId(layoutPageTemplateEntryId);
		}
	}

	@Override
	public long getFragmentEntryLayoutTemplateLinkId() {
		return _fragmentEntryLayoutTemplateLinkId;
	}

	@Override
	public void setFragmentEntryLayoutTemplateLinkId(
		long fragmentEntryLayoutTemplateLinkId) {
		_fragmentEntryLayoutTemplateLinkId = fragmentEntryLayoutTemplateLinkId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getFragmentEntryId() {
		return _fragmentEntryId;
	}

	@Override
	public void setFragmentEntryId(long fragmentEntryId) {
		_columnBitmask |= FRAGMENTENTRYID_COLUMN_BITMASK;

		if (!_setOriginalFragmentEntryId) {
			_setOriginalFragmentEntryId = true;

			_originalFragmentEntryId = _fragmentEntryId;
		}

		_fragmentEntryId = fragmentEntryId;
	}

	public long getOriginalFragmentEntryId() {
		return _originalFragmentEntryId;
	}

	@Override
	public long getLayoutPageTemplateEntryId() {
		return _layoutPageTemplateEntryId;
	}

	@Override
	public void setLayoutPageTemplateEntryId(long layoutPageTemplateEntryId) {
		_columnBitmask |= LAYOUTPAGETEMPLATEENTRYID_COLUMN_BITMASK;

		if (!_setOriginalLayoutPageTemplateEntryId) {
			_setOriginalLayoutPageTemplateEntryId = true;

			_originalLayoutPageTemplateEntryId = _layoutPageTemplateEntryId;
		}

		_layoutPageTemplateEntryId = layoutPageTemplateEntryId;
	}

	public long getOriginalLayoutPageTemplateEntryId() {
		return _originalLayoutPageTemplateEntryId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			FragmentEntryLayoutTemplateLink.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FragmentEntryLayoutTemplateLink toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (FragmentEntryLayoutTemplateLink)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FragmentEntryLayoutTemplateLinkImpl fragmentEntryLayoutTemplateLinkImpl = new FragmentEntryLayoutTemplateLinkImpl();

		fragmentEntryLayoutTemplateLinkImpl.setFragmentEntryLayoutTemplateLinkId(getFragmentEntryLayoutTemplateLinkId());
		fragmentEntryLayoutTemplateLinkImpl.setGroupId(getGroupId());
		fragmentEntryLayoutTemplateLinkImpl.setFragmentEntryId(getFragmentEntryId());
		fragmentEntryLayoutTemplateLinkImpl.setLayoutPageTemplateEntryId(getLayoutPageTemplateEntryId());

		fragmentEntryLayoutTemplateLinkImpl.resetOriginalValues();

		return fragmentEntryLayoutTemplateLinkImpl;
	}

	@Override
	public int compareTo(
		FragmentEntryLayoutTemplateLink fragmentEntryLayoutTemplateLink) {
		long primaryKey = fragmentEntryLayoutTemplateLink.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof FragmentEntryLayoutTemplateLink)) {
			return false;
		}

		FragmentEntryLayoutTemplateLink fragmentEntryLayoutTemplateLink = (FragmentEntryLayoutTemplateLink)obj;

		long primaryKey = fragmentEntryLayoutTemplateLink.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		FragmentEntryLayoutTemplateLinkModelImpl fragmentEntryLayoutTemplateLinkModelImpl =
			this;

		fragmentEntryLayoutTemplateLinkModelImpl._originalGroupId = fragmentEntryLayoutTemplateLinkModelImpl._groupId;

		fragmentEntryLayoutTemplateLinkModelImpl._setOriginalGroupId = false;

		fragmentEntryLayoutTemplateLinkModelImpl._originalFragmentEntryId = fragmentEntryLayoutTemplateLinkModelImpl._fragmentEntryId;

		fragmentEntryLayoutTemplateLinkModelImpl._setOriginalFragmentEntryId = false;

		fragmentEntryLayoutTemplateLinkModelImpl._originalLayoutPageTemplateEntryId = fragmentEntryLayoutTemplateLinkModelImpl._layoutPageTemplateEntryId;

		fragmentEntryLayoutTemplateLinkModelImpl._setOriginalLayoutPageTemplateEntryId = false;

		fragmentEntryLayoutTemplateLinkModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<FragmentEntryLayoutTemplateLink> toCacheModel() {
		FragmentEntryLayoutTemplateLinkCacheModel fragmentEntryLayoutTemplateLinkCacheModel =
			new FragmentEntryLayoutTemplateLinkCacheModel();

		fragmentEntryLayoutTemplateLinkCacheModel.fragmentEntryLayoutTemplateLinkId = getFragmentEntryLayoutTemplateLinkId();

		fragmentEntryLayoutTemplateLinkCacheModel.groupId = getGroupId();

		fragmentEntryLayoutTemplateLinkCacheModel.fragmentEntryId = getFragmentEntryId();

		fragmentEntryLayoutTemplateLinkCacheModel.layoutPageTemplateEntryId = getLayoutPageTemplateEntryId();

		return fragmentEntryLayoutTemplateLinkCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{fragmentEntryLayoutTemplateLinkId=");
		sb.append(getFragmentEntryLayoutTemplateLinkId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", fragmentEntryId=");
		sb.append(getFragmentEntryId());
		sb.append(", layoutPageTemplateEntryId=");
		sb.append(getLayoutPageTemplateEntryId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.liferay.fragment.model.FragmentEntryLayoutTemplateLink");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>fragmentEntryLayoutTemplateLinkId</column-name><column-value><![CDATA[");
		sb.append(getFragmentEntryLayoutTemplateLinkId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fragmentEntryId</column-name><column-value><![CDATA[");
		sb.append(getFragmentEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>layoutPageTemplateEntryId</column-name><column-value><![CDATA[");
		sb.append(getLayoutPageTemplateEntryId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = FragmentEntryLayoutTemplateLink.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			FragmentEntryLayoutTemplateLink.class
		};
	private long _fragmentEntryLayoutTemplateLinkId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _fragmentEntryId;
	private long _originalFragmentEntryId;
	private boolean _setOriginalFragmentEntryId;
	private long _layoutPageTemplateEntryId;
	private long _originalLayoutPageTemplateEntryId;
	private boolean _setOriginalLayoutPageTemplateEntryId;
	private long _columnBitmask;
	private FragmentEntryLayoutTemplateLink _escapedModel;
}