/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.fragment.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.fragment.model.FragmentLayoutTemplateLink;
import com.liferay.fragment.model.FragmentLayoutTemplateLinkModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the FragmentLayoutTemplateLink service. Represents a row in the &quot;FragmentLayoutTemplateLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link FragmentLayoutTemplateLinkModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FragmentLayoutTemplateLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FragmentLayoutTemplateLinkImpl
 * @see FragmentLayoutTemplateLink
 * @see FragmentLayoutTemplateLinkModel
 * @generated
 */
@ProviderType
public class FragmentLayoutTemplateLinkModelImpl extends BaseModelImpl<FragmentLayoutTemplateLink>
	implements FragmentLayoutTemplateLinkModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a fragment layout template link model instance should use the {@link FragmentLayoutTemplateLink} interface instead.
	 */
	public static final String TABLE_NAME = "FragmentLayoutTemplateLink";
	public static final Object[][] TABLE_COLUMNS = {
			{ "fragmentLayoutTemplateLinkId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "fragmentEntryId", Types.BIGINT },
			{ "layoutPageTemplateEntryId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("fragmentLayoutTemplateLinkId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("fragmentEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("layoutPageTemplateEntryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table FragmentLayoutTemplateLink (fragmentLayoutTemplateLinkId LONG not null primary key,groupId LONG,fragmentEntryId LONG,layoutPageTemplateEntryId LONG)";
	public static final String TABLE_SQL_DROP = "drop table FragmentLayoutTemplateLink";
	public static final String ORDER_BY_JPQL = " ORDER BY fragmentLayoutTemplateLink.fragmentLayoutTemplateLinkId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY FragmentLayoutTemplateLink.fragmentLayoutTemplateLinkId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.fragment.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.fragment.model.FragmentLayoutTemplateLink"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.fragment.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.fragment.model.FragmentLayoutTemplateLink"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.fragment.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.fragment.model.FragmentLayoutTemplateLink"),
			true);
	public static final long FRAGMENTENTRYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long LAYOUTPAGETEMPLATEENTRYID_COLUMN_BITMASK = 4L;
	public static final long FRAGMENTLAYOUTTEMPLATELINKID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.fragment.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.fragment.model.FragmentLayoutTemplateLink"));

	public FragmentLayoutTemplateLinkModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _fragmentLayoutTemplateLinkId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFragmentLayoutTemplateLinkId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fragmentLayoutTemplateLinkId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return FragmentLayoutTemplateLink.class;
	}

	@Override
	public String getModelClassName() {
		return FragmentLayoutTemplateLink.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("fragmentLayoutTemplateLinkId",
			getFragmentLayoutTemplateLinkId());
		attributes.put("groupId", getGroupId());
		attributes.put("fragmentEntryId", getFragmentEntryId());
		attributes.put("layoutPageTemplateEntryId",
			getLayoutPageTemplateEntryId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long fragmentLayoutTemplateLinkId = (Long)attributes.get(
				"fragmentLayoutTemplateLinkId");

		if (fragmentLayoutTemplateLinkId != null) {
			setFragmentLayoutTemplateLinkId(fragmentLayoutTemplateLinkId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long fragmentEntryId = (Long)attributes.get("fragmentEntryId");

		if (fragmentEntryId != null) {
			setFragmentEntryId(fragmentEntryId);
		}

		Long layoutPageTemplateEntryId = (Long)attributes.get(
				"layoutPageTemplateEntryId");

		if (layoutPageTemplateEntryId != null) {
			setLayoutPageTemplateEntryId(layoutPageTemplateEntryId);
		}
	}

	@Override
	public long getFragmentLayoutTemplateLinkId() {
		return _fragmentLayoutTemplateLinkId;
	}

	@Override
	public void setFragmentLayoutTemplateLinkId(
		long fragmentLayoutTemplateLinkId) {
		_fragmentLayoutTemplateLinkId = fragmentLayoutTemplateLinkId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getFragmentEntryId() {
		return _fragmentEntryId;
	}

	@Override
	public void setFragmentEntryId(long fragmentEntryId) {
		_columnBitmask |= FRAGMENTENTRYID_COLUMN_BITMASK;

		if (!_setOriginalFragmentEntryId) {
			_setOriginalFragmentEntryId = true;

			_originalFragmentEntryId = _fragmentEntryId;
		}

		_fragmentEntryId = fragmentEntryId;
	}

	public long getOriginalFragmentEntryId() {
		return _originalFragmentEntryId;
	}

	@Override
	public long getLayoutPageTemplateEntryId() {
		return _layoutPageTemplateEntryId;
	}

	@Override
	public void setLayoutPageTemplateEntryId(long layoutPageTemplateEntryId) {
		_columnBitmask |= LAYOUTPAGETEMPLATEENTRYID_COLUMN_BITMASK;

		if (!_setOriginalLayoutPageTemplateEntryId) {
			_setOriginalLayoutPageTemplateEntryId = true;

			_originalLayoutPageTemplateEntryId = _layoutPageTemplateEntryId;
		}

		_layoutPageTemplateEntryId = layoutPageTemplateEntryId;
	}

	public long getOriginalLayoutPageTemplateEntryId() {
		return _originalLayoutPageTemplateEntryId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			FragmentLayoutTemplateLink.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public FragmentLayoutTemplateLink toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (FragmentLayoutTemplateLink)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FragmentLayoutTemplateLinkImpl fragmentLayoutTemplateLinkImpl = new FragmentLayoutTemplateLinkImpl();

		fragmentLayoutTemplateLinkImpl.setFragmentLayoutTemplateLinkId(getFragmentLayoutTemplateLinkId());
		fragmentLayoutTemplateLinkImpl.setGroupId(getGroupId());
		fragmentLayoutTemplateLinkImpl.setFragmentEntryId(getFragmentEntryId());
		fragmentLayoutTemplateLinkImpl.setLayoutPageTemplateEntryId(getLayoutPageTemplateEntryId());

		fragmentLayoutTemplateLinkImpl.resetOriginalValues();

		return fragmentLayoutTemplateLinkImpl;
	}

	@Override
	public int compareTo(FragmentLayoutTemplateLink fragmentLayoutTemplateLink) {
		long primaryKey = fragmentLayoutTemplateLink.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof FragmentLayoutTemplateLink)) {
			return false;
		}

		FragmentLayoutTemplateLink fragmentLayoutTemplateLink = (FragmentLayoutTemplateLink)obj;

		long primaryKey = fragmentLayoutTemplateLink.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		FragmentLayoutTemplateLinkModelImpl fragmentLayoutTemplateLinkModelImpl = this;

		fragmentLayoutTemplateLinkModelImpl._originalGroupId = fragmentLayoutTemplateLinkModelImpl._groupId;

		fragmentLayoutTemplateLinkModelImpl._setOriginalGroupId = false;

		fragmentLayoutTemplateLinkModelImpl._originalFragmentEntryId = fragmentLayoutTemplateLinkModelImpl._fragmentEntryId;

		fragmentLayoutTemplateLinkModelImpl._setOriginalFragmentEntryId = false;

		fragmentLayoutTemplateLinkModelImpl._originalLayoutPageTemplateEntryId = fragmentLayoutTemplateLinkModelImpl._layoutPageTemplateEntryId;

		fragmentLayoutTemplateLinkModelImpl._setOriginalLayoutPageTemplateEntryId = false;

		fragmentLayoutTemplateLinkModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<FragmentLayoutTemplateLink> toCacheModel() {
		FragmentLayoutTemplateLinkCacheModel fragmentLayoutTemplateLinkCacheModel =
			new FragmentLayoutTemplateLinkCacheModel();

		fragmentLayoutTemplateLinkCacheModel.fragmentLayoutTemplateLinkId = getFragmentLayoutTemplateLinkId();

		fragmentLayoutTemplateLinkCacheModel.groupId = getGroupId();

		fragmentLayoutTemplateLinkCacheModel.fragmentEntryId = getFragmentEntryId();

		fragmentLayoutTemplateLinkCacheModel.layoutPageTemplateEntryId = getLayoutPageTemplateEntryId();

		return fragmentLayoutTemplateLinkCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{fragmentLayoutTemplateLinkId=");
		sb.append(getFragmentLayoutTemplateLinkId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", fragmentEntryId=");
		sb.append(getFragmentEntryId());
		sb.append(", layoutPageTemplateEntryId=");
		sb.append(getLayoutPageTemplateEntryId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.liferay.fragment.model.FragmentLayoutTemplateLink");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>fragmentLayoutTemplateLinkId</column-name><column-value><![CDATA[");
		sb.append(getFragmentLayoutTemplateLinkId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fragmentEntryId</column-name><column-value><![CDATA[");
		sb.append(getFragmentEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>layoutPageTemplateEntryId</column-name><column-value><![CDATA[");
		sb.append(getLayoutPageTemplateEntryId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = FragmentLayoutTemplateLink.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			FragmentLayoutTemplateLink.class
		};
	private long _fragmentLayoutTemplateLinkId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _fragmentEntryId;
	private long _originalFragmentEntryId;
	private boolean _setOriginalFragmentEntryId;
	private long _layoutPageTemplateEntryId;
	private long _originalLayoutPageTemplateEntryId;
	private boolean _setOriginalLayoutPageTemplateEntryId;
	private long _columnBitmask;
	private FragmentLayoutTemplateLink _escapedModel;
}