##
## Test Suites
##

    modified.files.includes[relevant][frontend-taglib-sample-web-rule]=**
    relevant.rule.names=frontend-taglib-sample-web-rule

    #
    # Relevant
    #

    ignoreParents[relevant][frontend-taglib-sample-web-rule]=true

##
## Testray
##

    testray.main.component.name=User Interface