dependencies {
	testIntegrationCompile project(":apps:archived:document-library-file-rank-api")
	testIntegrationCompile project(":apps:document-library:document-library-test-util")
	testIntegrationCompile project(":apps:trash:trash-api")
	testIntegrationCompile project(":test:arquillian-extension-junit-bridge")
}