/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the AssetEntryAssetTagRel service. Represents a row in the &quot;AssetEntryAssetTagRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.asset.model.impl.AssetEntryAssetTagRelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.asset.model.impl.AssetEntryAssetTagRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetEntryAssetTagRel
 * @see com.liferay.asset.model.impl.AssetEntryAssetTagRelImpl
 * @see com.liferay.asset.model.impl.AssetEntryAssetTagRelModelImpl
 * @generated
 */
@ProviderType
public interface AssetEntryAssetTagRelModel extends BaseModel<AssetEntryAssetTagRel>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset entry asset tag rel model instance should use the {@link AssetEntryAssetTagRel} interface instead.
	 */

	/**
	 * Returns the primary key of this asset entry asset tag rel.
	 *
	 * @return the primary key of this asset entry asset tag rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset entry asset tag rel.
	 *
	 * @param primaryKey the primary key of this asset entry asset tag rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the entry ID of this asset entry asset tag rel.
	 *
	 * @return the entry ID of this asset entry asset tag rel
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this asset entry asset tag rel.
	 *
	 * @param entryId the entry ID of this asset entry asset tag rel
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the company ID of this asset entry asset tag rel.
	 *
	 * @return the company ID of this asset entry asset tag rel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this asset entry asset tag rel.
	 *
	 * @param companyId the company ID of this asset entry asset tag rel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the asset entry ID of this asset entry asset tag rel.
	 *
	 * @return the asset entry ID of this asset entry asset tag rel
	 */
	public long getAssetEntryId();

	/**
	 * Sets the asset entry ID of this asset entry asset tag rel.
	 *
	 * @param assetEntryId the asset entry ID of this asset entry asset tag rel
	 */
	public void setAssetEntryId(long assetEntryId);

	/**
	 * Returns the asset tag ID of this asset entry asset tag rel.
	 *
	 * @return the asset tag ID of this asset entry asset tag rel
	 */
	public long getAssetTagId();

	/**
	 * Sets the asset tag ID of this asset entry asset tag rel.
	 *
	 * @param assetTagId the asset tag ID of this asset entry asset tag rel
	 */
	public void setAssetTagId(long assetTagId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AssetEntryAssetTagRel assetEntryAssetTagRel);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AssetEntryAssetTagRel> toCacheModel();

	@Override
	public AssetEntryAssetTagRel toEscapedModel();

	@Override
	public AssetEntryAssetTagRel toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}