/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.fragment.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.fragment.model.FragmentLayoutTemplateLink;
import com.liferay.fragment.service.FragmentLayoutTemplateLinkLocalService;
import com.liferay.fragment.service.persistence.FragmentEntryPersistence;
import com.liferay.fragment.service.persistence.FragmentLayoutTemplateLinkPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the fragment layout template link local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.fragment.service.impl.FragmentLayoutTemplateLinkLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.fragment.service.impl.FragmentLayoutTemplateLinkLocalServiceImpl
 * @see com.liferay.fragment.service.FragmentLayoutTemplateLinkLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class FragmentLayoutTemplateLinkLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements FragmentLayoutTemplateLinkLocalService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.fragment.service.FragmentLayoutTemplateLinkLocalServiceUtil} to access the fragment layout template link local service.
	 */

	/**
	 * Adds the fragment layout template link to the database. Also notifies the appropriate model listeners.
	 *
	 * @param fragmentLayoutTemplateLink the fragment layout template link
	 * @return the fragment layout template link that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FragmentLayoutTemplateLink addFragmentLayoutTemplateLink(
		FragmentLayoutTemplateLink fragmentLayoutTemplateLink) {
		fragmentLayoutTemplateLink.setNew(true);

		return fragmentLayoutTemplateLinkPersistence.update(fragmentLayoutTemplateLink);
	}

	/**
	 * Creates a new fragment layout template link with the primary key. Does not add the fragment layout template link to the database.
	 *
	 * @param fragmentLayoutTemplateLinkId the primary key for the new fragment layout template link
	 * @return the new fragment layout template link
	 */
	@Override
	public FragmentLayoutTemplateLink createFragmentLayoutTemplateLink(
		long fragmentLayoutTemplateLinkId) {
		return fragmentLayoutTemplateLinkPersistence.create(fragmentLayoutTemplateLinkId);
	}

	/**
	 * Deletes the fragment layout template link with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param fragmentLayoutTemplateLinkId the primary key of the fragment layout template link
	 * @return the fragment layout template link that was removed
	 * @throws PortalException if a fragment layout template link with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FragmentLayoutTemplateLink deleteFragmentLayoutTemplateLink(
		long fragmentLayoutTemplateLinkId) throws PortalException {
		return fragmentLayoutTemplateLinkPersistence.remove(fragmentLayoutTemplateLinkId);
	}

	/**
	 * Deletes the fragment layout template link from the database. Also notifies the appropriate model listeners.
	 *
	 * @param fragmentLayoutTemplateLink the fragment layout template link
	 * @return the fragment layout template link that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public FragmentLayoutTemplateLink deleteFragmentLayoutTemplateLink(
		FragmentLayoutTemplateLink fragmentLayoutTemplateLink) {
		return fragmentLayoutTemplateLinkPersistence.remove(fragmentLayoutTemplateLink);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(FragmentLayoutTemplateLink.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return fragmentLayoutTemplateLinkPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.fragment.model.impl.FragmentLayoutTemplateLinkModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return fragmentLayoutTemplateLinkPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.fragment.model.impl.FragmentLayoutTemplateLinkModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return fragmentLayoutTemplateLinkPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return fragmentLayoutTemplateLinkPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return fragmentLayoutTemplateLinkPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public FragmentLayoutTemplateLink fetchFragmentLayoutTemplateLink(
		long fragmentLayoutTemplateLinkId) {
		return fragmentLayoutTemplateLinkPersistence.fetchByPrimaryKey(fragmentLayoutTemplateLinkId);
	}

	/**
	 * Returns the fragment layout template link with the primary key.
	 *
	 * @param fragmentLayoutTemplateLinkId the primary key of the fragment layout template link
	 * @return the fragment layout template link
	 * @throws PortalException if a fragment layout template link with the primary key could not be found
	 */
	@Override
	public FragmentLayoutTemplateLink getFragmentLayoutTemplateLink(
		long fragmentLayoutTemplateLinkId) throws PortalException {
		return fragmentLayoutTemplateLinkPersistence.findByPrimaryKey(fragmentLayoutTemplateLinkId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(fragmentLayoutTemplateLinkLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FragmentLayoutTemplateLink.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"fragmentLayoutTemplateLinkId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(fragmentLayoutTemplateLinkLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(FragmentLayoutTemplateLink.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"fragmentLayoutTemplateLinkId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(fragmentLayoutTemplateLinkLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(FragmentLayoutTemplateLink.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"fragmentLayoutTemplateLinkId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return fragmentLayoutTemplateLinkLocalService.deleteFragmentLayoutTemplateLink((FragmentLayoutTemplateLink)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return fragmentLayoutTemplateLinkPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the fragment layout template links.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.fragment.model.impl.FragmentLayoutTemplateLinkModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of fragment layout template links
	 * @param end the upper bound of the range of fragment layout template links (not inclusive)
	 * @return the range of fragment layout template links
	 */
	@Override
	public List<FragmentLayoutTemplateLink> getFragmentLayoutTemplateLinks(
		int start, int end) {
		return fragmentLayoutTemplateLinkPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of fragment layout template links.
	 *
	 * @return the number of fragment layout template links
	 */
	@Override
	public int getFragmentLayoutTemplateLinksCount() {
		return fragmentLayoutTemplateLinkPersistence.countAll();
	}

	/**
	 * Updates the fragment layout template link in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param fragmentLayoutTemplateLink the fragment layout template link
	 * @return the fragment layout template link that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public FragmentLayoutTemplateLink updateFragmentLayoutTemplateLink(
		FragmentLayoutTemplateLink fragmentLayoutTemplateLink) {
		return fragmentLayoutTemplateLinkPersistence.update(fragmentLayoutTemplateLink);
	}

	/**
	 * Returns the fragment layout template link local service.
	 *
	 * @return the fragment layout template link local service
	 */
	public FragmentLayoutTemplateLinkLocalService getFragmentLayoutTemplateLinkLocalService() {
		return fragmentLayoutTemplateLinkLocalService;
	}

	/**
	 * Sets the fragment layout template link local service.
	 *
	 * @param fragmentLayoutTemplateLinkLocalService the fragment layout template link local service
	 */
	public void setFragmentLayoutTemplateLinkLocalService(
		FragmentLayoutTemplateLinkLocalService fragmentLayoutTemplateLinkLocalService) {
		this.fragmentLayoutTemplateLinkLocalService = fragmentLayoutTemplateLinkLocalService;
	}

	/**
	 * Returns the fragment layout template link persistence.
	 *
	 * @return the fragment layout template link persistence
	 */
	public FragmentLayoutTemplateLinkPersistence getFragmentLayoutTemplateLinkPersistence() {
		return fragmentLayoutTemplateLinkPersistence;
	}

	/**
	 * Sets the fragment layout template link persistence.
	 *
	 * @param fragmentLayoutTemplateLinkPersistence the fragment layout template link persistence
	 */
	public void setFragmentLayoutTemplateLinkPersistence(
		FragmentLayoutTemplateLinkPersistence fragmentLayoutTemplateLinkPersistence) {
		this.fragmentLayoutTemplateLinkPersistence = fragmentLayoutTemplateLinkPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the fragment entry local service.
	 *
	 * @return the fragment entry local service
	 */
	public com.liferay.fragment.service.FragmentEntryLocalService getFragmentEntryLocalService() {
		return fragmentEntryLocalService;
	}

	/**
	 * Sets the fragment entry local service.
	 *
	 * @param fragmentEntryLocalService the fragment entry local service
	 */
	public void setFragmentEntryLocalService(
		com.liferay.fragment.service.FragmentEntryLocalService fragmentEntryLocalService) {
		this.fragmentEntryLocalService = fragmentEntryLocalService;
	}

	/**
	 * Returns the fragment entry persistence.
	 *
	 * @return the fragment entry persistence
	 */
	public FragmentEntryPersistence getFragmentEntryPersistence() {
		return fragmentEntryPersistence;
	}

	/**
	 * Sets the fragment entry persistence.
	 *
	 * @param fragmentEntryPersistence the fragment entry persistence
	 */
	public void setFragmentEntryPersistence(
		FragmentEntryPersistence fragmentEntryPersistence) {
		this.fragmentEntryPersistence = fragmentEntryPersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.fragment.model.FragmentLayoutTemplateLink",
			fragmentLayoutTemplateLinkLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.fragment.model.FragmentLayoutTemplateLink");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return FragmentLayoutTemplateLinkLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return FragmentLayoutTemplateLink.class;
	}

	protected String getModelClassName() {
		return FragmentLayoutTemplateLink.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = fragmentLayoutTemplateLinkPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = FragmentLayoutTemplateLinkLocalService.class)
	protected FragmentLayoutTemplateLinkLocalService fragmentLayoutTemplateLinkLocalService;
	@BeanReference(type = FragmentLayoutTemplateLinkPersistence.class)
	protected FragmentLayoutTemplateLinkPersistence fragmentLayoutTemplateLinkPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@BeanReference(type = com.liferay.fragment.service.FragmentEntryLocalService.class)
	protected com.liferay.fragment.service.FragmentEntryLocalService fragmentEntryLocalService;
	@BeanReference(type = FragmentEntryPersistence.class)
	protected FragmentEntryPersistence fragmentEntryPersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}