/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.html.preview.service.base;

import com.liferay.html.preview.model.HtmlPreview;
import com.liferay.html.preview.service.HtmlPreviewService;
import com.liferay.html.preview.service.persistence.HtmlPreviewPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the html preview remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.html.preview.service.impl.HtmlPreviewServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.html.preview.service.impl.HtmlPreviewServiceImpl
 * @see com.liferay.html.preview.service.HtmlPreviewServiceUtil
 * @generated
 */
public abstract class HtmlPreviewServiceBaseImpl extends BaseServiceImpl
	implements HtmlPreviewService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.html.preview.service.HtmlPreviewServiceUtil} to access the html preview remote service.
	 */

	/**
	 * Returns the html preview local service.
	 *
	 * @return the html preview local service
	 */
	public com.liferay.html.preview.service.HtmlPreviewLocalService getHtmlPreviewLocalService() {
		return htmlPreviewLocalService;
	}

	/**
	 * Sets the html preview local service.
	 *
	 * @param htmlPreviewLocalService the html preview local service
	 */
	public void setHtmlPreviewLocalService(
		com.liferay.html.preview.service.HtmlPreviewLocalService htmlPreviewLocalService) {
		this.htmlPreviewLocalService = htmlPreviewLocalService;
	}

	/**
	 * Returns the html preview remote service.
	 *
	 * @return the html preview remote service
	 */
	public HtmlPreviewService getHtmlPreviewService() {
		return htmlPreviewService;
	}

	/**
	 * Sets the html preview remote service.
	 *
	 * @param htmlPreviewService the html preview remote service
	 */
	public void setHtmlPreviewService(HtmlPreviewService htmlPreviewService) {
		this.htmlPreviewService = htmlPreviewService;
	}

	/**
	 * Returns the html preview persistence.
	 *
	 * @return the html preview persistence
	 */
	public HtmlPreviewPersistence getHtmlPreviewPersistence() {
		return htmlPreviewPersistence;
	}

	/**
	 * Sets the html preview persistence.
	 *
	 * @param htmlPreviewPersistence the html preview persistence
	 */
	public void setHtmlPreviewPersistence(
		HtmlPreviewPersistence htmlPreviewPersistence) {
		this.htmlPreviewPersistence = htmlPreviewPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return HtmlPreviewService.class.getName();
	}

	protected Class<?> getModelClass() {
		return HtmlPreview.class;
	}

	protected String getModelClassName() {
		return HtmlPreview.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = htmlPreviewPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.html.preview.service.HtmlPreviewLocalService.class)
	protected com.liferay.html.preview.service.HtmlPreviewLocalService htmlPreviewLocalService;
	@BeanReference(type = HtmlPreviewService.class)
	protected HtmlPreviewService htmlPreviewService;
	@BeanReference(type = HtmlPreviewPersistence.class)
	protected HtmlPreviewPersistence htmlPreviewPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}