/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.asset.model.AssetEntryAssetTagRel;
import com.liferay.asset.service.AssetEntryAssetTagRelLocalService;
import com.liferay.asset.service.persistence.AssetEntryAssetTagRelPersistence;
import com.liferay.asset.service.persistence.AssetEntryPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the asset entry asset tag rel local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.asset.service.impl.AssetEntryAssetTagRelLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.asset.service.impl.AssetEntryAssetTagRelLocalServiceImpl
 * @see com.liferay.asset.service.AssetEntryAssetTagRelLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class AssetEntryAssetTagRelLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements AssetEntryAssetTagRelLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.asset.service.AssetEntryAssetTagRelLocalServiceUtil} to access the asset entry asset tag rel local service.
	 */

	/**
	 * Adds the asset entry asset tag rel to the database. Also notifies the appropriate model listeners.
	 *
	 * @param assetEntryAssetTagRel the asset entry asset tag rel
	 * @return the asset entry asset tag rel that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssetEntryAssetTagRel addAssetEntryAssetTagRel(
		AssetEntryAssetTagRel assetEntryAssetTagRel) {
		assetEntryAssetTagRel.setNew(true);

		return assetEntryAssetTagRelPersistence.update(assetEntryAssetTagRel);
	}

	/**
	 * Creates a new asset entry asset tag rel with the primary key. Does not add the asset entry asset tag rel to the database.
	 *
	 * @param entryId the primary key for the new asset entry asset tag rel
	 * @return the new asset entry asset tag rel
	 */
	@Override
	public AssetEntryAssetTagRel createAssetEntryAssetTagRel(long entryId) {
		return assetEntryAssetTagRelPersistence.create(entryId);
	}

	/**
	 * Deletes the asset entry asset tag rel with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param entryId the primary key of the asset entry asset tag rel
	 * @return the asset entry asset tag rel that was removed
	 * @throws PortalException if a asset entry asset tag rel with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssetEntryAssetTagRel deleteAssetEntryAssetTagRel(long entryId)
		throws PortalException {
		return assetEntryAssetTagRelPersistence.remove(entryId);
	}

	/**
	 * Deletes the asset entry asset tag rel from the database. Also notifies the appropriate model listeners.
	 *
	 * @param assetEntryAssetTagRel the asset entry asset tag rel
	 * @return the asset entry asset tag rel that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssetEntryAssetTagRel deleteAssetEntryAssetTagRel(
		AssetEntryAssetTagRel assetEntryAssetTagRel) {
		return assetEntryAssetTagRelPersistence.remove(assetEntryAssetTagRel);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(AssetEntryAssetTagRel.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return assetEntryAssetTagRelPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.asset.model.impl.AssetEntryAssetTagRelModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return assetEntryAssetTagRelPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.asset.model.impl.AssetEntryAssetTagRelModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return assetEntryAssetTagRelPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return assetEntryAssetTagRelPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return assetEntryAssetTagRelPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public AssetEntryAssetTagRel fetchAssetEntryAssetTagRel(long entryId) {
		return assetEntryAssetTagRelPersistence.fetchByPrimaryKey(entryId);
	}

	/**
	 * Returns the asset entry asset tag rel with the primary key.
	 *
	 * @param entryId the primary key of the asset entry asset tag rel
	 * @return the asset entry asset tag rel
	 * @throws PortalException if a asset entry asset tag rel with the primary key could not be found
	 */
	@Override
	public AssetEntryAssetTagRel getAssetEntryAssetTagRel(long entryId)
		throws PortalException {
		return assetEntryAssetTagRelPersistence.findByPrimaryKey(entryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(assetEntryAssetTagRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AssetEntryAssetTagRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("entryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(assetEntryAssetTagRelLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AssetEntryAssetTagRel.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("entryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(assetEntryAssetTagRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AssetEntryAssetTagRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("entryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return assetEntryAssetTagRelLocalService.deleteAssetEntryAssetTagRel((AssetEntryAssetTagRel)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return assetEntryAssetTagRelPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the asset entry asset tag rels.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.asset.model.impl.AssetEntryAssetTagRelModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of asset entry asset tag rels
	 * @param end the upper bound of the range of asset entry asset tag rels (not inclusive)
	 * @return the range of asset entry asset tag rels
	 */
	@Override
	public List<AssetEntryAssetTagRel> getAssetEntryAssetTagRels(int start,
		int end) {
		return assetEntryAssetTagRelPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of asset entry asset tag rels.
	 *
	 * @return the number of asset entry asset tag rels
	 */
	@Override
	public int getAssetEntryAssetTagRelsCount() {
		return assetEntryAssetTagRelPersistence.countAll();
	}

	/**
	 * Updates the asset entry asset tag rel in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param assetEntryAssetTagRel the asset entry asset tag rel
	 * @return the asset entry asset tag rel that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssetEntryAssetTagRel updateAssetEntryAssetTagRel(
		AssetEntryAssetTagRel assetEntryAssetTagRel) {
		return assetEntryAssetTagRelPersistence.update(assetEntryAssetTagRel);
	}

	/**
	 * Returns the asset entry asset tag rel local service.
	 *
	 * @return the asset entry asset tag rel local service
	 */
	public AssetEntryAssetTagRelLocalService getAssetEntryAssetTagRelLocalService() {
		return assetEntryAssetTagRelLocalService;
	}

	/**
	 * Sets the asset entry asset tag rel local service.
	 *
	 * @param assetEntryAssetTagRelLocalService the asset entry asset tag rel local service
	 */
	public void setAssetEntryAssetTagRelLocalService(
		AssetEntryAssetTagRelLocalService assetEntryAssetTagRelLocalService) {
		this.assetEntryAssetTagRelLocalService = assetEntryAssetTagRelLocalService;
	}

	/**
	 * Returns the asset entry asset tag rel persistence.
	 *
	 * @return the asset entry asset tag rel persistence
	 */
	public AssetEntryAssetTagRelPersistence getAssetEntryAssetTagRelPersistence() {
		return assetEntryAssetTagRelPersistence;
	}

	/**
	 * Sets the asset entry asset tag rel persistence.
	 *
	 * @param assetEntryAssetTagRelPersistence the asset entry asset tag rel persistence
	 */
	public void setAssetEntryAssetTagRelPersistence(
		AssetEntryAssetTagRelPersistence assetEntryAssetTagRelPersistence) {
		this.assetEntryAssetTagRelPersistence = assetEntryAssetTagRelPersistence;
	}

	/**
	 * Returns the asset entry local service.
	 *
	 * @return the asset entry local service
	 */
	public com.liferay.asset.service.AssetEntryLocalService getAssetEntryLocalService() {
		return assetEntryLocalService;
	}

	/**
	 * Sets the asset entry local service.
	 *
	 * @param assetEntryLocalService the asset entry local service
	 */
	public void setAssetEntryLocalService(
		com.liferay.asset.service.AssetEntryLocalService assetEntryLocalService) {
		this.assetEntryLocalService = assetEntryLocalService;
	}

	/**
	 * Returns the asset entry persistence.
	 *
	 * @return the asset entry persistence
	 */
	public AssetEntryPersistence getAssetEntryPersistence() {
		return assetEntryPersistence;
	}

	/**
	 * Sets the asset entry persistence.
	 *
	 * @param assetEntryPersistence the asset entry persistence
	 */
	public void setAssetEntryPersistence(
		AssetEntryPersistence assetEntryPersistence) {
		this.assetEntryPersistence = assetEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.asset.model.AssetEntryAssetTagRel",
			assetEntryAssetTagRelLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.asset.model.AssetEntryAssetTagRel");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AssetEntryAssetTagRelLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AssetEntryAssetTagRel.class;
	}

	protected String getModelClassName() {
		return AssetEntryAssetTagRel.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = assetEntryAssetTagRelPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = AssetEntryAssetTagRelLocalService.class)
	protected AssetEntryAssetTagRelLocalService assetEntryAssetTagRelLocalService;
	@BeanReference(type = AssetEntryAssetTagRelPersistence.class)
	protected AssetEntryAssetTagRelPersistence assetEntryAssetTagRelPersistence;
	@BeanReference(type = com.liferay.asset.service.AssetEntryLocalService.class)
	protected com.liferay.asset.service.AssetEntryLocalService assetEntryLocalService;
	@BeanReference(type = AssetEntryPersistence.class)
	protected AssetEntryPersistence assetEntryPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}