/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.fragment.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the FragmentEntryLayoutTemplateLink service. Represents a row in the &quot;FragmentEntryLayoutTemplateLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.fragment.model.impl.FragmentEntryLayoutTemplateLinkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.fragment.model.impl.FragmentEntryLayoutTemplateLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FragmentEntryLayoutTemplateLink
 * @see com.liferay.fragment.model.impl.FragmentEntryLayoutTemplateLinkImpl
 * @see com.liferay.fragment.model.impl.FragmentEntryLayoutTemplateLinkModelImpl
 * @generated
 */
@ProviderType
public interface FragmentEntryLayoutTemplateLinkModel extends BaseModel<FragmentEntryLayoutTemplateLink> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fragment entry layout template link model instance should use the {@link FragmentEntryLayoutTemplateLink} interface instead.
	 */

	/**
	 * Returns the primary key of this fragment entry layout template link.
	 *
	 * @return the primary key of this fragment entry layout template link
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fragment entry layout template link.
	 *
	 * @param primaryKey the primary key of this fragment entry layout template link
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the fragment entry layout template link ID of this fragment entry layout template link.
	 *
	 * @return the fragment entry layout template link ID of this fragment entry layout template link
	 */
	public long getFragmentEntryLayoutTemplateLinkId();

	/**
	 * Sets the fragment entry layout template link ID of this fragment entry layout template link.
	 *
	 * @param fragmentEntryLayoutTemplateLinkId the fragment entry layout template link ID of this fragment entry layout template link
	 */
	public void setFragmentEntryLayoutTemplateLinkId(
		long fragmentEntryLayoutTemplateLinkId);

	/**
	 * Returns the group ID of this fragment entry layout template link.
	 *
	 * @return the group ID of this fragment entry layout template link
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this fragment entry layout template link.
	 *
	 * @param groupId the group ID of this fragment entry layout template link
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the fragment entry ID of this fragment entry layout template link.
	 *
	 * @return the fragment entry ID of this fragment entry layout template link
	 */
	public long getFragmentEntryId();

	/**
	 * Sets the fragment entry ID of this fragment entry layout template link.
	 *
	 * @param fragmentEntryId the fragment entry ID of this fragment entry layout template link
	 */
	public void setFragmentEntryId(long fragmentEntryId);

	/**
	 * Returns the layout page template entry ID of this fragment entry layout template link.
	 *
	 * @return the layout page template entry ID of this fragment entry layout template link
	 */
	public long getLayoutPageTemplateEntryId();

	/**
	 * Sets the layout page template entry ID of this fragment entry layout template link.
	 *
	 * @param layoutPageTemplateEntryId the layout page template entry ID of this fragment entry layout template link
	 */
	public void setLayoutPageTemplateEntryId(long layoutPageTemplateEntryId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		FragmentEntryLayoutTemplateLink fragmentEntryLayoutTemplateLink);

	@Override
	public int hashCode();

	@Override
	public CacheModel<FragmentEntryLayoutTemplateLink> toCacheModel();

	@Override
	public FragmentEntryLayoutTemplateLink toEscapedModel();

	@Override
	public FragmentEntryLayoutTemplateLink toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}