create table ClientExtensionEntry (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	externalReferenceCode VARCHAR(75) null,
	clientExtensionEntryId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	customElementCSSURLs VARCHAR(75) null,
	customElementHTMLElementName VARCHAR(75) null,
	customElementURLs VARCHAR(75) null,
	customElementUseESM BOOLEAN,
	description VARCHAR(75) null,
	friendlyURLMapping VARCHAR(75) null,
	iFrameURL VARCHAR(75) null,
	instanceable BOOLEAN,
	name STRING null,
	portletCategoryName VARCHAR(75) null,
	properties VARCHAR(75) null,
	sourceCodeURL VARCHAR(75) null,
	themeCSSMainURL VARCHAR(75) null,
	themeCSSPortalURL VARCHAR(75) null,
	themeFaviconURL VARCHAR(75) null,
	themeJSURLs VARCHAR(75) null,
	type_ VARCHAR(75) null,
	typeSettings TEXT null,
	status INTEGER,
	statusByUserId LONG,
	statusByUserName VARCHAR(75) null,
	statusDate DATE null
);

create table ClientExtensionEntryRel (
	mvccVersion LONG default 0 not null,
	uuid_ VARCHAR(75) null,
	externalReferenceCode VARCHAR(75) null,
	clientExtensionEntryRelId LONG not null primary key,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	classNameId LONG,
	classPK LONG,
	clientExtensionName VARCHAR(75) null,
	type_ VARCHAR(75) null
);