/* global fetch, FormData, Liferay, location */

import Component from 'metal-component';
import {Config} from 'metal-state';
import Soy from 'metal-soy';

import 'metal-modal';
import templates from './SimpleInputModal.soy';

/**
 * SimpleInputModal
 */
class SimpleInputModal extends Component {
	/**
	 * @inheritDoc
	 */
	disposed() {
		this.emit('disposed');
	}

	/**
	 * Callback executed when the SimpleInputModal cancel button
	 * has been clicked.
	 * @private
	 */
	_handleCancelButtonClick() {
		this.dispose();
	}

	/**
	 * Callback executed when the SimpleInputModal form has been
	 * submited and it receives a server error as response.
	 * It emits a formError event with the errorMessage received.
	 * @param {Response} response
	 * @private
	 */
	_handleFormError(responseContent) {
		this._errorMessage = responseContent.error || '';
		this.emit('formError', { errorMessage: this._errorMessage });
	}

	/**
	 * Callback executed when the SimpleInputModal form has been
	 * submited. It prevents the default behaviour and sends this form
	 * using a fetch request.
	 * @param {Event} event
	 * @private
	 */
	_handleFormSubmit(event) {
		event.preventDefault();

		const form = event.delegateTarget;

		fetch(this.formSubmitURL, {
			body: new FormData(form),
			credentials: 'include',
			method: 'POST',
		})
			.then((response) => response.json())
			.then((responseContent) => {
				if (responseContent.error) {
					this._handleFormError(responseContent);
				} else {
					this._handleFormSuccess(responseContent);
				}
			})
			.catch((response) => {
				this._handleFormError(response);
			});

		this.emit('formSubmit');
	}

	/**
	 * Callback executed when the SimpleInputModal form has been
	 * submited and it receives a server successful response.
	 * It emits a formSuccess event with the redirectURL received.
	 * @param {Response} response
	 * @private
	 */
	_handleFormSuccess(responseContent) {
		this.emit('formSuccess', {
			redirectURL: responseContent.redirectURL || ''
		});

		if (responseContent.redirectURL) {
			if (Liferay.SPA) {
				Liferay.SPA.app.navigate(responseContent.redirectURL);
			} else {
				location.href = responseContent.redirectURL;
			}
		} else {
			this.dispose();
		}
	}

	/**
	 * Callback executed when the modal visibility property changes
	 * @private
	 */
	_handleModalVisibleChanged() {
		this.dispose();
	}
}

/**
 * State definition.
 * @type {!Object}
 * @static
 */
SimpleInputModal.STATE = {
	/**
	 * Label for the optional checkbox
	 * @default ''
	 * @instance
	 * @memberOf SimpleInputModal
	 * @type {string}
	 */
	checkboxFieldLabel: Config.string().value(''),

	/**
	 * Name for the optional checkbox
	 * @default ''
	 * @instance
	 * @memberOf SimpleInputModal
	 * @type {string}
	 */
	checkboxFieldName: Config.string().value(''),

	/**
	 * Initial value for the optional checkbox
	 * @default false
	 * @instance
	 * @memberOf SimpleInputModal
	 * @type {boolean}
	 */
	checkboxFieldValue: Config.bool().value(false),

	/**
	 * Modal window title
	 * @default undefined
	 * @instance
	 * @memberOf SimpleInputModal
	 * @type {!string}
	 */
	dialogTitle: Config.string().required(),

	/**
	 * URL where the form will be submitted to
	 * @default undefined
	 * @instance
	 * @memberOf SimpleInputModal
	 * @type {!string}
	 */
	formSubmitURL: Config.string().required(),

	/**
	 * Autogenerated id provided by templates
	 * @default ''
	 * @instance
	 * @memberOf SimpleInputModal
	 * @type {string}
	 */
	id: Config.string().value(''),

	/**
	 * Name for the hidden id field
	 * @default ''
	 * @instance
	 * @memberOf SimpleInputModal
	 * @type {string}
	 */
	idFieldName: Config.string().value(''),

	/**
	 * Value for the hidden id field
	 * @default ''
	 * @instance
	 * @memberOf SimpleInputModal
	 * @type {string}
	 */
	idFieldValue: Config.string().value(''),

	/**
	 * Label for the main field
	 * @default undefined
	 * @instance
	 * @memberOf SimpleInputModal
	 * @type {!string}
	 */
	mainFieldLabel: Config.string().required(),

	/**
	 * Name for the main field
	 * @default undefined
	 * @instance
	 * @memberOf SimpleInputModal
	 * @type {!string}
	 */
	mainFieldName: Config.string().required(),

	/**
	 * Placeholder for the main field
	 * @default ''
	 * @instance
	 * @memberOf SimpleInputModal
	 * @type {string}
	 */
	mainFieldPlaceholder: Config.string().value(''),

	/**
	 * Initial value for the main field
	 * @default ''
	 * @instance
	 * @memberOf SimpleInputModal
	 * @type {string}
	 */
	mainFieldValue: Config.string().value(''),

	/**
	 * Namespace that will be prepended to field names
	 * @default undefined
	 * @instance
	 * @memberOf SimpleInputModal
	 * @type {!string}
	 */
	namespace: Config.string().required(),

	/**
	 * URL for the portal icons being used
	 * @default undefined
	 * @instance
	 * @memberOf SimpleInputModal
	 * @type {!string}
	 */
	spritemap: Config.string().required(),

	/**
	 * Form error message returned by the server
	 * @default ''
	 * @instance
	 * @memberOf SimpleInputModal
	 * @private
	 * @type {!string}
	 */
	_errorMessage: Config.string().internal().value(''),
};

Soy.register(SimpleInputModal, templates);

export {SimpleInputModal};
export default SimpleInputModal;
