/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.entry.rel.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.asset.entry.rel.model.AssetEntryClassNameRel;
import com.liferay.asset.entry.rel.service.AssetEntryClassNameRelLocalService;
import com.liferay.asset.entry.rel.service.persistence.AssetEntryClassNameRelPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the asset entry class name rel local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.asset.entry.rel.service.impl.AssetEntryClassNameRelLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.asset.entry.rel.service.impl.AssetEntryClassNameRelLocalServiceImpl
 * @see com.liferay.asset.entry.rel.service.AssetEntryClassNameRelLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class AssetEntryClassNameRelLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements AssetEntryClassNameRelLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.asset.entry.rel.service.AssetEntryClassNameRelLocalServiceUtil} to access the asset entry class name rel local service.
	 */

	/**
	 * Adds the asset entry class name rel to the database. Also notifies the appropriate model listeners.
	 *
	 * @param assetEntryClassNameRel the asset entry class name rel
	 * @return the asset entry class name rel that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssetEntryClassNameRel addAssetEntryClassNameRel(
		AssetEntryClassNameRel assetEntryClassNameRel) {
		assetEntryClassNameRel.setNew(true);

		return assetEntryClassNameRelPersistence.update(assetEntryClassNameRel);
	}

	/**
	 * Creates a new asset entry class name rel with the primary key. Does not add the asset entry class name rel to the database.
	 *
	 * @param assetEntryClassNameRelId the primary key for the new asset entry class name rel
	 * @return the new asset entry class name rel
	 */
	@Override
	@Transactional(enabled = false)
	public AssetEntryClassNameRel createAssetEntryClassNameRel(
		long assetEntryClassNameRelId) {
		return assetEntryClassNameRelPersistence.create(assetEntryClassNameRelId);
	}

	/**
	 * Deletes the asset entry class name rel with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param assetEntryClassNameRelId the primary key of the asset entry class name rel
	 * @return the asset entry class name rel that was removed
	 * @throws PortalException if a asset entry class name rel with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssetEntryClassNameRel deleteAssetEntryClassNameRel(
		long assetEntryClassNameRelId) throws PortalException {
		return assetEntryClassNameRelPersistence.remove(assetEntryClassNameRelId);
	}

	/**
	 * Deletes the asset entry class name rel from the database. Also notifies the appropriate model listeners.
	 *
	 * @param assetEntryClassNameRel the asset entry class name rel
	 * @return the asset entry class name rel that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AssetEntryClassNameRel deleteAssetEntryClassNameRel(
		AssetEntryClassNameRel assetEntryClassNameRel) {
		return assetEntryClassNameRelPersistence.remove(assetEntryClassNameRel);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(AssetEntryClassNameRel.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return assetEntryClassNameRelPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.asset.entry.rel.model.impl.AssetEntryClassNameRelModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return assetEntryClassNameRelPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.asset.entry.rel.model.impl.AssetEntryClassNameRelModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return assetEntryClassNameRelPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return assetEntryClassNameRelPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return assetEntryClassNameRelPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public AssetEntryClassNameRel fetchAssetEntryClassNameRel(
		long assetEntryClassNameRelId) {
		return assetEntryClassNameRelPersistence.fetchByPrimaryKey(assetEntryClassNameRelId);
	}

	/**
	 * Returns the asset entry class name rel with the primary key.
	 *
	 * @param assetEntryClassNameRelId the primary key of the asset entry class name rel
	 * @return the asset entry class name rel
	 * @throws PortalException if a asset entry class name rel with the primary key could not be found
	 */
	@Override
	public AssetEntryClassNameRel getAssetEntryClassNameRel(
		long assetEntryClassNameRelId) throws PortalException {
		return assetEntryClassNameRelPersistence.findByPrimaryKey(assetEntryClassNameRelId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(assetEntryClassNameRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AssetEntryClassNameRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"assetEntryClassNameRelId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(assetEntryClassNameRelLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AssetEntryClassNameRel.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"assetEntryClassNameRelId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(assetEntryClassNameRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AssetEntryClassNameRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"assetEntryClassNameRelId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return assetEntryClassNameRelLocalService.deleteAssetEntryClassNameRel((AssetEntryClassNameRel)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return assetEntryClassNameRelPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the asset entry class name rels.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.asset.entry.rel.model.impl.AssetEntryClassNameRelModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of asset entry class name rels
	 * @param end the upper bound of the range of asset entry class name rels (not inclusive)
	 * @return the range of asset entry class name rels
	 */
	@Override
	public List<AssetEntryClassNameRel> getAssetEntryClassNameRels(int start,
		int end) {
		return assetEntryClassNameRelPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of asset entry class name rels.
	 *
	 * @return the number of asset entry class name rels
	 */
	@Override
	public int getAssetEntryClassNameRelsCount() {
		return assetEntryClassNameRelPersistence.countAll();
	}

	/**
	 * Updates the asset entry class name rel in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param assetEntryClassNameRel the asset entry class name rel
	 * @return the asset entry class name rel that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AssetEntryClassNameRel updateAssetEntryClassNameRel(
		AssetEntryClassNameRel assetEntryClassNameRel) {
		return assetEntryClassNameRelPersistence.update(assetEntryClassNameRel);
	}

	/**
	 * Returns the asset entry class name rel local service.
	 *
	 * @return the asset entry class name rel local service
	 */
	public AssetEntryClassNameRelLocalService getAssetEntryClassNameRelLocalService() {
		return assetEntryClassNameRelLocalService;
	}

	/**
	 * Sets the asset entry class name rel local service.
	 *
	 * @param assetEntryClassNameRelLocalService the asset entry class name rel local service
	 */
	public void setAssetEntryClassNameRelLocalService(
		AssetEntryClassNameRelLocalService assetEntryClassNameRelLocalService) {
		this.assetEntryClassNameRelLocalService = assetEntryClassNameRelLocalService;
	}

	/**
	 * Returns the asset entry class name rel persistence.
	 *
	 * @return the asset entry class name rel persistence
	 */
	public AssetEntryClassNameRelPersistence getAssetEntryClassNameRelPersistence() {
		return assetEntryClassNameRelPersistence;
	}

	/**
	 * Sets the asset entry class name rel persistence.
	 *
	 * @param assetEntryClassNameRelPersistence the asset entry class name rel persistence
	 */
	public void setAssetEntryClassNameRelPersistence(
		AssetEntryClassNameRelPersistence assetEntryClassNameRelPersistence) {
		this.assetEntryClassNameRelPersistence = assetEntryClassNameRelPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.asset.entry.rel.model.AssetEntryClassNameRel",
			assetEntryClassNameRelLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.asset.entry.rel.model.AssetEntryClassNameRel");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AssetEntryClassNameRelLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AssetEntryClassNameRel.class;
	}

	protected String getModelClassName() {
		return AssetEntryClassNameRel.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = assetEntryClassNameRelPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = AssetEntryClassNameRelLocalService.class)
	protected AssetEntryClassNameRelLocalService assetEntryClassNameRelLocalService;
	@BeanReference(type = AssetEntryClassNameRelPersistence.class)
	protected AssetEntryClassNameRelPersistence assetEntryClassNameRelPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}