/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.asset.model.AssetEntryAssetTagRel;
import com.liferay.asset.model.AssetEntryAssetTagRelModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the AssetEntryAssetTagRel service. Represents a row in the &quot;AssetEntryAssetTagRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AssetEntryAssetTagRelModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssetEntryAssetTagRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetEntryAssetTagRelImpl
 * @see AssetEntryAssetTagRel
 * @see AssetEntryAssetTagRelModel
 * @generated
 */
@ProviderType
public class AssetEntryAssetTagRelModelImpl extends BaseModelImpl<AssetEntryAssetTagRel>
	implements AssetEntryAssetTagRelModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a asset entry asset tag rel model instance should use the {@link AssetEntryAssetTagRel} interface instead.
	 */
	public static final String TABLE_NAME = "AssetEntryAssetTagRel";
	public static final Object[][] TABLE_COLUMNS = {
			{ "entryId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "assetEntryId", Types.BIGINT },
			{ "assetTagId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("entryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("assetEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("assetTagId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table AssetEntryAssetTagRel (entryId LONG not null primary key,companyId LONG,assetEntryId LONG,assetTagId LONG)";
	public static final String TABLE_SQL_DROP = "drop table AssetEntryAssetTagRel";
	public static final String ORDER_BY_JPQL = " ORDER BY assetEntryAssetTagRel.entryId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY AssetEntryAssetTagRel.entryId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.asset.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.asset.model.AssetEntryAssetTagRel"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.asset.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.asset.model.AssetEntryAssetTagRel"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.asset.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.asset.model.AssetEntryAssetTagRel"),
			true);
	public static final long ASSETENTRYID_COLUMN_BITMASK = 1L;
	public static final long ASSETTAGID_COLUMN_BITMASK = 2L;
	public static final long ENTRYID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.asset.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.asset.model.AssetEntryAssetTagRel"));

	public AssetEntryAssetTagRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _entryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _entryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AssetEntryAssetTagRel.class;
	}

	@Override
	public String getModelClassName() {
		return AssetEntryAssetTagRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("entryId", getEntryId());
		attributes.put("companyId", getCompanyId());
		attributes.put("assetEntryId", getAssetEntryId());
		attributes.put("assetTagId", getAssetTagId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long entryId = (Long)attributes.get("entryId");

		if (entryId != null) {
			setEntryId(entryId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long assetEntryId = (Long)attributes.get("assetEntryId");

		if (assetEntryId != null) {
			setAssetEntryId(assetEntryId);
		}

		Long assetTagId = (Long)attributes.get("assetTagId");

		if (assetTagId != null) {
			setAssetTagId(assetTagId);
		}
	}

	@Override
	public long getEntryId() {
		return _entryId;
	}

	@Override
	public void setEntryId(long entryId) {
		_entryId = entryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getAssetEntryId() {
		return _assetEntryId;
	}

	@Override
	public void setAssetEntryId(long assetEntryId) {
		_columnBitmask |= ASSETENTRYID_COLUMN_BITMASK;

		if (!_setOriginalAssetEntryId) {
			_setOriginalAssetEntryId = true;

			_originalAssetEntryId = _assetEntryId;
		}

		_assetEntryId = assetEntryId;
	}

	public long getOriginalAssetEntryId() {
		return _originalAssetEntryId;
	}

	@Override
	public long getAssetTagId() {
		return _assetTagId;
	}

	@Override
	public void setAssetTagId(long assetTagId) {
		_columnBitmask |= ASSETTAGID_COLUMN_BITMASK;

		if (!_setOriginalAssetTagId) {
			_setOriginalAssetTagId = true;

			_originalAssetTagId = _assetTagId;
		}

		_assetTagId = assetTagId;
	}

	public long getOriginalAssetTagId() {
		return _originalAssetTagId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			AssetEntryAssetTagRel.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AssetEntryAssetTagRel toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AssetEntryAssetTagRel)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AssetEntryAssetTagRelImpl assetEntryAssetTagRelImpl = new AssetEntryAssetTagRelImpl();

		assetEntryAssetTagRelImpl.setEntryId(getEntryId());
		assetEntryAssetTagRelImpl.setCompanyId(getCompanyId());
		assetEntryAssetTagRelImpl.setAssetEntryId(getAssetEntryId());
		assetEntryAssetTagRelImpl.setAssetTagId(getAssetTagId());

		assetEntryAssetTagRelImpl.resetOriginalValues();

		return assetEntryAssetTagRelImpl;
	}

	@Override
	public int compareTo(AssetEntryAssetTagRel assetEntryAssetTagRel) {
		long primaryKey = assetEntryAssetTagRel.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AssetEntryAssetTagRel)) {
			return false;
		}

		AssetEntryAssetTagRel assetEntryAssetTagRel = (AssetEntryAssetTagRel)obj;

		long primaryKey = assetEntryAssetTagRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		AssetEntryAssetTagRelModelImpl assetEntryAssetTagRelModelImpl = this;

		assetEntryAssetTagRelModelImpl._originalAssetEntryId = assetEntryAssetTagRelModelImpl._assetEntryId;

		assetEntryAssetTagRelModelImpl._setOriginalAssetEntryId = false;

		assetEntryAssetTagRelModelImpl._originalAssetTagId = assetEntryAssetTagRelModelImpl._assetTagId;

		assetEntryAssetTagRelModelImpl._setOriginalAssetTagId = false;

		assetEntryAssetTagRelModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<AssetEntryAssetTagRel> toCacheModel() {
		AssetEntryAssetTagRelCacheModel assetEntryAssetTagRelCacheModel = new AssetEntryAssetTagRelCacheModel();

		assetEntryAssetTagRelCacheModel.entryId = getEntryId();

		assetEntryAssetTagRelCacheModel.companyId = getCompanyId();

		assetEntryAssetTagRelCacheModel.assetEntryId = getAssetEntryId();

		assetEntryAssetTagRelCacheModel.assetTagId = getAssetTagId();

		return assetEntryAssetTagRelCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{entryId=");
		sb.append(getEntryId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", assetEntryId=");
		sb.append(getAssetEntryId());
		sb.append(", assetTagId=");
		sb.append(getAssetTagId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.liferay.asset.model.AssetEntryAssetTagRel");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>entryId</column-name><column-value><![CDATA[");
		sb.append(getEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assetEntryId</column-name><column-value><![CDATA[");
		sb.append(getAssetEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assetTagId</column-name><column-value><![CDATA[");
		sb.append(getAssetTagId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = AssetEntryAssetTagRel.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			AssetEntryAssetTagRel.class
		};
	private long _entryId;
	private long _companyId;
	private long _assetEntryId;
	private long _originalAssetEntryId;
	private boolean _setOriginalAssetEntryId;
	private long _assetTagId;
	private long _originalAssetTagId;
	private boolean _setOriginalAssetTagId;
	private long _columnBitmask;
	private AssetEntryAssetTagRel _escapedModel;
}